steps:
  - name: gcr.io/cloud-builders/docker
    args: [
      'build',
      '-t',
      '$_IMAGE_NAME:$COMMIT_SHA',
       '.',
      '--build-arg',
       'value=${_ENV_MODE}',
      '--build-arg',
       'exposeportvalue=${_ENV_EXPOSE_PORT}',
       '-f',
       $_DOCKERFILE_NAME
    ]

    dir: $_DOCKERFILE_DIR
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_IMAGE_NAME:$COMMIT_SHA'
    id: Push
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - prepare
      - '--filename=$_K8S_YAML_PATH'
      - '--image=$_IMAGE_NAME:$COMMIT_SHA'
      - '--app=$_K8S_APP_NAME'
      - '--version=$COMMIT_SHA'
      - '--namespace=$_K8S_NAMESPACE'
      - '--label=$_K8S_LABELS'
      - '--annotation=$_K8S_ANNOTATIONS,gcb-build-id=$BUILD_ID'
      - '--output=output'
    id: Prepare deploy
  - name: gcr.io/cloud-builders/gsutil
    entrypoint: sh
    args:
      - '-c'
      - |-
        if [ "$_OUTPUT_BUCKET_PATH" != "" ]
        then
          gsutil cp -r output/suggested gs://$_OUTPUT_BUCKET_PATH/config/$BUILD_ID/suggested
          echo "Copied suggested base configs to gs://$_OUTPUT_BUCKET_PATH/config/$BUILD_ID/suggested"
          gsutil cp -r output/expanded gs://$_OUTPUT_BUCKET_PATH/config/$BUILD_ID/expanded
          echo "Copied expanded configs to gs://$_OUTPUT_BUCKET_PATH/config/$BUILD_ID/expanded"
        fi
    id: Save configs & Apply deploy
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - apply
      - '--filename=output/expanded'
      - '--cluster=$_GKE_CLUSTER'
      - '--location=$_GKE_LOCATION'
      - '--namespace=$_K8S_NAMESPACE'
images:
  - '$_IMAGE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _K8S_LABELS: ''
  _IMAGE_NAME: gcr.io/stable-balancer-329910/react-frontend-dev
  _K8S_YAML_PATH: kubernetes/deployment-dev.yml
  _DOCKERFILE_NAME: Dockerfile
  _OUTPUT_BUCKET_PATH: react-k8s-gcp/deploy
  _K8S_NAMESPACE: dev
  _GKE_CLUSTER: react-k8s-gcp-cluster
  _DOCKERFILE_DIR: ''
  _GKE_LOCATION: asia-east1-a
  _K8S_ANNOTATIONS: gcb-trigger-id=96032f23-ed85-444e-96ef-17088607b24c
  _K8S_APP_NAME: react-frontend
tags:
  - gcp-cloud-build-deploy
  - $_K8S_APP_NAME